spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 660696398371-ksr7addn5gmartgb04jpdu1e8u8oejec.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: maybeags@gmail.com
  secret_key: study-springboot
